import json
from app.services.v6_research_evidence_ui import research_evidence_ui

def test_ui_consolidates_durable_status_without_live_unlock(tmp_path):
    marker=tmp_path/"marker.json";members=tmp_path/"members.jsonl";cache=tmp_path/"cache.json";history=tmp_path/"history.jsonl"
    marker.write_text(json.dumps({"cohort":"v6_forward_only","started_at":"2026-09-15T00:00:00+00:00"}),encoding="utf-8")
    members.write_text(json.dumps({"event":"membership","trade_id":"t1","entry_timestamp":"2026-09-15T01:00:00+00:00","challengers":["trend_regime"],"pre_entry_snapshot":{"regime":"TREND_UP"}})+"\n",encoding="utf-8")
    cache.write_text(json.dumps({"forward_evidence":{"trend_regime":{"closed":25,"positive_expectancy":True}},"shadow_paper":{"prospective_nomination_count":1}}),encoding="utf-8")
    history.write_text(json.dumps({"event":"v6_forward_evidence_snapshot","timestamp":"2026-09-15T02:00:00+00:00","evidence":{"forward":{"trend_regime":{"closed":25,"expectancy":0.1,"uncertainty_supports_positive_edge":False}},"exit_replay":{"path_coverage":0.4},"shadow_paper":{"prospective_nomination_count":1}}})+"\n",encoding="utf-8")
    r=research_evidence_ui(history_path=history,marker_path=marker,membership_path=members,scorecard_cache_path=cache)
    assert r["mode"]=="LIGHTWEIGHT_DURABLE_READ_ONLY";assert r["readiness_progress"]["forward"]["trend_regime"]["closed"]==25;assert r["evidence"]["snapshot_count"]==1
    assert r["diversity"]["snapshot_available"] is True;assert r["longitudinal_diversity"]["candidates"]["trend_regime"]["snapshot_count"]==1
    assert r["fixed_window_diversity"]["method"]=="PREDECLARED_7_DAY_POINT_IN_TIME"
    mw=r["multi_window_diversity"];assert mw["method"]=="PREDECLARED_3D_7D_14D_POINT_IN_TIME";assert mw["all_windows_reported"] is True;assert mw["best_window_selection"] is False
    assert [x["days"] for x in mw["predeclared_windows"]]==[3,7,14]
    c=mw["candidates"]["trend_regime"];assert set(c["windows"])=={"3","7","14"};assert c["selected_best_window"] is None
    assert c["windows"]["3"]["minimum_window_memberships"]==10;assert c["windows"]["7"]["minimum_window_memberships"]==20;assert c["windows"]["14"]["minimum_window_memberships"]==30
    mh=r["multi_window_consistency_history"];assert mh["method"]=="PROSPECTIVE_NEW_EVIDENCE_ONLY_3D_7D_14D";assert mh["best_window_selection"] is False
    hc=mh["candidates"]["trend_regime"];assert hc["observation_count"]==1;assert hc["duplicate_refresh_resistant"] is True;assert hc["new_evidence_required"] is True
    assert set(hc["latest"]["windows"])=={"3","7","14"}
    ch=r["consistency_change_diagnostics"];assert ch["method"]=="DESCRIPTIVE_NEW_EVIDENCE_TRANSITIONS";assert ch["automatic_scoring"] is False;assert ch["best_window_selection"] is False
    cc=ch["candidates"]["trend_regime"];assert cc["observation_count"]==1;assert cc["transition_count"]==0;assert cc["new_evidence_only"] is True;assert cc["production_promoted"] is False
    pd=r["transition_persistence_diagnostics"];assert pd["method"]=="DESCRIPTIVE_NEXT_NEW_EVIDENCE_CONFIRMATION";assert pd["minimum_observations_required"]==3;assert pd["automatic_scoring"] is False;assert pd["best_window_selection"] is False
    pc=pd["candidates"]["trend_regime"];assert pc["observation_count"]==1;assert pc["confirmation_check_count"]==0;assert pc["minimum_observations_required"]==3;assert pc["new_evidence_only"] is True;assert pc["production_promoted"] is False
    sd=r["confirmation_sequence_diagnostics"];assert sd["method"]=="DESCRIPTIVE_CONFIRMATION_SEQUENCE";assert sd["minimum_observations_required"]==3;assert sd["automatic_scoring"] is False;assert sd["best_window_selection"] is False
    sc=sd["candidates"]["trend_regime"];assert sc["observation_count"]==1;assert sc["confirmation_check_count"]==0;assert sc["minimum_observations_required"]==3;assert set(sc["windows"])=={"3","7","14"};assert sc["disagreement_sequence"]==[];assert sc["production_promoted"] is False
    eg=r["evidence_sufficiency_gaps"];assert eg["method"]=="DESCRIPTIVE_EVIDENCE_GAPS";assert eg["readiness_score"] is None;assert eg["automatic_scoring"] is False;assert eg["best_window_selection"] is False
    gc=eg["candidates"]["trend_regime"];assert gc["observation_count"]==1;assert gc["minimum_observations_required"]==3;assert gc["confirmation_observation_gap"]==2;assert gc["confirmation_layer_sufficient"] is False;assert set(gc["windows"])=={"3","7","14"}
    assert gc["windows"]["3"]["current_memberships"]==1;assert gc["windows"]["3"]["required_memberships"]==10;assert gc["windows"]["3"]["membership_gap"]==9
    assert gc["windows"]["7"]["required_memberships"]==20;assert gc["windows"]["14"]["required_memberships"]==30
    em=r["research_evidence_maturity"];assert em["method"]=="DESCRIPTIVE_MATURITY_PRESENCE_MISSING";assert em["aggregate_score"] is None;assert em["readiness_percentage"] is None;assert em["automatic_scoring"] is False;assert em["weighted_scoring"] is False
    mc=em["candidates"]["trend_regime"];assert set(mc["dimensions"])=={"forward_sample","uncertainty_support","stability","diversity","longitudinal_history","multi_window_evidence","confirmation_depth","gap_closure"};assert mc["dimensions"]["forward_sample"]["state"]=="PRESENT";assert mc["dimensions"]["uncertainty_support"]["state"]=="MISSING";assert mc["aggregate_score"] is None;assert mc["readiness_percentage"] is None
    mt=r["maturity_change_history"];assert mt["method"]=="DESCRIPTIVE_MATURITY_NEW_EVIDENCE_TRANSITIONS";assert mt["automatic_scoring"] is False;assert mt["weighted_scoring"] is False;assert mt["readiness_percentage"] is None
    mtc=mt["candidates"]["trend_regime"];assert mtc["observation_count"]==1;assert mtc["transition_count"]==0;assert mtc["duplicate_refresh_resistant"] is True;assert mtc["new_evidence_only"] is True;assert mtc["production_promoted"] is False
    mp=r["maturity_transition_persistence"];assert mp["method"]=="DESCRIPTIVE_MATURITY_NEXT_NEW_EVIDENCE_CONFIRMATION";assert mp["minimum_observations_required"]==3;assert mp["automatic_scoring"] is False;assert mp["weighted_scoring"] is False;assert mp["readiness_percentage"] is None
    mpc=mp["candidates"]["trend_regime"];assert mpc["observation_count"]==1;assert mpc["confirmation_check_count"]==0;assert mpc["minimum_observations_required"]==3;assert mpc["duplicate_refresh_resistant"] is True;assert mpc["new_evidence_only"] is True;assert mpc["production_promoted"] is False
    ms=r["maturity_confirmation_sequence_diagnostics"];assert ms["method"]=="DESCRIPTIVE_MATURITY_CONFIRMATION_SEQUENCE";assert ms["minimum_observations_required"]==3;assert ms["automatic_scoring"] is False;assert ms["weighted_scoring"] is False;assert ms["readiness_percentage"] is None
    msc=ms["candidates"]["trend_regime"];assert msc["observation_count"]==1;assert msc["confirmation_check_count"]==0;assert msc["minimum_observations_required"]==3;assert set(msc["dimensions"])==set(ms["dimensions"]);assert msc["duplicate_refresh_resistant"] is True;assert msc["new_evidence_only"] is True;assert msc["production_promoted"] is False
    mss=r["maturity_sequence_stability_diagnostics"];assert mss["method"]=="DESCRIPTIVE_MATURITY_SEQUENCE_STABILITY";assert mss["minimum_observations_required"]==3;assert mss["automatic_scoring"] is False;assert mss["weighted_scoring"] is False;assert mss["readiness_percentage"] is None
    mssc=mss["candidates"]["trend_regime"];assert mssc["observation_count"]==1;assert mssc["confirmation_check_count"]==0;assert set(mssc["dimensions"])==set(mss["dimensions"]);assert mssc["dimensions"]["forward_sample"]["pattern"]=="INSUFFICIENT_HISTORY";assert mssc["dimensions"]["forward_sample"]["repeated_latest"] is False
    assert r["heavy_research_recompute"] is False;assert r["separation"]["multi_window_diversity_is_trading_readiness"] is False;assert r["separation"]["multi_window_consistency_history_is_trading_readiness"] is False;assert r["separation"]["consistency_change_diagnostics_is_trading_readiness"] is False;assert r["separation"]["transition_persistence_diagnostics_is_trading_readiness"] is False;assert r["separation"]["confirmation_sequence_diagnostics_is_trading_readiness"] is False;assert r["separation"]["evidence_sufficiency_gaps_is_trading_readiness"] is False;assert r["separation"]["research_evidence_maturity_is_trading_readiness"] is False;assert r["separation"]["maturity_change_history_is_trading_readiness"] is False;assert r["separation"]["maturity_transition_persistence_is_trading_readiness"] is False;assert r["separation"]["maturity_confirmation_sequence_diagnostics_is_trading_readiness"] is False;assert r["separation"]["maturity_sequence_stability_diagnostics_is_trading_readiness"] is False;assert r["trading_readiness"]=="NOT_READY";assert r["live_capital_allowed"] is False;assert r["automatic_real_money_execution"] is False

def test_ui_missing_durable_files_fails_closed(tmp_path):
    r=research_evidence_ui(history_path=tmp_path/"history.jsonl",marker_path=tmp_path/"marker.json",membership_path=tmp_path/"members.jsonl",scorecard_cache_path=tmp_path/"cache.json")
    assert r["evidence"]["snapshot_count"]==0;assert r["stability"]["human_review_eligible"]==[];assert r["diversity"]["snapshot_available"] is False;assert r["longitudinal_diversity"]["candidates"]=={};assert r["fixed_window_diversity"]["candidates"]=={};assert r["multi_window_diversity"]["snapshot_available"] is False;assert r["multi_window_diversity"]["candidates"]=={};assert r["multi_window_consistency_history"]["snapshot_count"]==0;assert r["multi_window_consistency_history"]["candidates"]=={};assert r["consistency_change_diagnostics"]["candidates"]=={};assert r["consistency_change_diagnostics"]["automatic_scoring"] is False;assert r["transition_persistence_diagnostics"]["candidates"]=={};assert r["transition_persistence_diagnostics"]["automatic_scoring"] is False;assert r["confirmation_sequence_diagnostics"]["candidates"]=={};assert r["confirmation_sequence_diagnostics"]["automatic_scoring"] is False;assert r["evidence_sufficiency_gaps"]["candidates"]=={};assert r["evidence_sufficiency_gaps"]["readiness_score"] is None;assert r["research_evidence_maturity"]["candidates"]=={};assert r["research_evidence_maturity"]["aggregate_score"] is None;assert r["research_evidence_maturity"]["readiness_percentage"] is None;assert r["maturity_change_history"]["candidates"]=={};assert r["maturity_change_history"]["readiness_percentage"] is None;assert r["maturity_transition_persistence"]["candidates"]=={};assert r["maturity_transition_persistence"]["readiness_percentage"] is None;assert r["maturity_confirmation_sequence_diagnostics"]["candidates"]=={};assert r["maturity_confirmation_sequence_diagnostics"]["readiness_percentage"] is None;assert r["maturity_sequence_stability_diagnostics"]["candidates"]=={};assert r["maturity_sequence_stability_diagnostics"]["readiness_percentage"] is None;assert r["normal_command_center_recompute"] is False;assert r["automatic_promotion"] is False;assert r["live_capital_allowed"] is False
